### ISSUE TITLE
php 7.3 hprose扩展安装编译失败

### ISSUE THREAD

**Issue by tekintian** [hprose/hprose#13]
php 7.3 hprose扩展安装编译失败， 错误代码：

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuseraiheej/hprose-1.6.6/libtool --mod                                                                                             e=compile cc  -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-b                                                                                             uild-defaultuseraiheej/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultu                                                                                             seraiheej/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/                                                                                             usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/ph                                                                                             p/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fsta                                                                                             ck-protector-strong -fpic -fpie -O2 -DHAVE_CONFIG_H  -fstack-protector-strong -f                                                                                             pic -fpie -O2   -c /tmp/pear/temp/hprose/php_hprose.c -o php_hprose.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defau                                                                                             ltuseraiheej/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuseraiheej/                                                                                             hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/                                                                                             include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/                                                                                             usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protecto                                                                                             r-strong -fpic -fpie -O2 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O                                                                                             2 -c /tmp/pear/temp/hprose/php_hprose.c  -fPIC -DPIC -o .libs/php_hprose.o
/bin/bash /tmp/pear/temp/pear-build-defaultuseraiheej/hprose-1.6.6/libtool --mod                                                                                             e=compile cc  -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-b                                                                                             uild-defaultuseraiheej/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultu                                                                                             seraiheej/hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/                                                                                             usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/ph                                                                                             p/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fsta                                                                                             ck-protector-strong -fpic -fpie -O2 -DHAVE_CONFIG_H  -fstack-protector-strong -f                                                                                             pic -fpie -O2   -c /tmp/pear/temp/hprose/hprose_common.c -o hprose_common.lo
 cc -I. -I/tmp/pear/temp/hprose -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defau                                                                                             ltuseraiheej/hprose-1.6.6/include -I/tmp/pear/temp/pear-build-defaultuseraiheej/                                                                                             hprose-1.6.6/main -I/tmp/pear/temp/hprose -I/usr/local/include/php -I/usr/local/                                                                                             include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/                                                                                             usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protecto                                                                                             r-strong -fpic -fpie -O2 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O                                                                                             2 -c /tmp/pear/temp/hprose/hprose_common.c  -fPIC -DPIC -o .libs/hprose_common.o
/tmp/pear/temp/hprose/hprose_common.c: In function '__get_fcall_info_cache':
/tmp/pear/temp/hprose/hprose_common.c:166:46: warning: format '%s' expects argum                                                                                             ent of type 'char *', but argument 4 has type 'zend_string * {aka struct _zend_s                                                                                             tring *}' [-Wformat=]
                                     "Method %s::%s() does not exist", ce->name,                                                                                              fname);
                                              ^
/tmp/pear/temp/hprose/hprose_common.c:202:8: error: 'zend_fcall_info_cache {aka                                                                                              struct _zend_fcall_info_cache}' has no member named 'initialized'
     fcc.initialized = 1;
        ^
/tmp/pear/temp/hprose/hprose_common.c: In function '__create_php_object':
/tmp/pear/temp/hprose/hprose_common.c:764:12: error: 'zend_fcall_info_cache {aka                                                                                              struct _zend_fcall_info_cache}' has no member named 'initialized'
         fcc.initialized = 1;
            ^
make: *** [Makefile:196: hprose_common.lo] Error 1
ERROR: `make' failed

**Comment by andot** [comment]
感谢反馈

**Comment by andot** [comment]
此问题已解决，安装新版本即可。
